package commands

import (
	"math"
	"time"

	"github.com/jesseduffield/lazydocker/pkg/domain"
)

// statsFromDomain projects a domain.Stats snapshot back onto the legacy
// ContainerStats struct that user graph configs reference by JSON path
// (e.g. "ClientStats.CPUStats.CPUUsage.TotalUsage"). Only the fields the
// runtime abstraction surfaces are populated; the rest stay at the zero
// value. The percentage calculators below depend only on populated
// fields and therefore keep working.
func statsFromDomain(s domain.Stats) ContainerStats {
	out := ContainerStats{
		Read:    s.Time,
		Preread: s.Time, // domain.Stats does not carry a pre-read timestamp
	}
	out.CPUStats.CPUUsage.TotalUsage = int64(s.CPU.TotalUsage)
	out.CPUStats.SystemCPUUsage = int64(s.CPU.SystemUsage)
	out.CPUStats.OnlineCpus = int(s.CPU.OnlineCPUs)
	if len(s.CPU.PerCPUUsage) > 0 {
		out.CPUStats.CPUUsage.PercpuUsage = make([]int64, 0, len(s.CPU.PerCPUUsage))
		for _, v := range s.CPU.PerCPUUsage {
			out.CPUStats.CPUUsage.PercpuUsage = append(out.CPUStats.CPUUsage.PercpuUsage, int64(v))
		}
	}
	out.PrecpuStats.CPUUsage.TotalUsage = int64(s.PreCPU.TotalUsage)
	out.PrecpuStats.SystemCPUUsage = int64(s.PreCPU.SystemUsage)
	out.PrecpuStats.OnlineCpus = int(s.PreCPU.OnlineCPUs)
	if len(s.PreCPU.PerCPUUsage) > 0 {
		out.PrecpuStats.CPUUsage.PercpuUsage = make([]int64, 0, len(s.PreCPU.PerCPUUsage))
		for _, v := range s.PreCPU.PerCPUUsage {
			out.PrecpuStats.CPUUsage.PercpuUsage = append(out.PrecpuStats.CPUUsage.PercpuUsage, int64(v))
		}
	}

	out.MemoryStats.Usage = int(s.Memory.Usage)
	out.MemoryStats.MaxUsage = int(s.Memory.MaxUsage)
	out.MemoryStats.Limit = int64(s.Memory.Limit)

	// Network breakdown — the upstream struct hard-codes eth0; mirror
	// whichever interface comes first in the snapshot so the legacy graph
	// path "Networks.Eth0.RxBytes" keeps working for the common case.
	for _, n := range s.Networks {
		out.Networks.Eth0.RxBytes = int(n.RxBytes)
		out.Networks.Eth0.RxPackets = int(n.RxPackets)
		out.Networks.Eth0.RxErrors = int(n.RxErrors)
		out.Networks.Eth0.RxDropped = int(n.RxDropped)
		out.Networks.Eth0.TxBytes = int(n.TxBytes)
		out.Networks.Eth0.TxPackets = int(n.TxPackets)
		out.Networks.Eth0.TxErrors = int(n.TxErrors)
		out.Networks.Eth0.TxDropped = int(n.TxDropped)
		break
	}
	return out
}

// RecordedStats contains both the container stats we've received from docker, and our own derived stats  from those container stats. When configuring a graph, you're basically specifying the path of a value in this struct
type RecordedStats struct {
	ClientStats  ContainerStats
	DerivedStats DerivedStats
	RecordedAt   time.Time
}

// DerivedStats contains some useful stats that we've calculated based on the raw container stats that we got back from docker
type DerivedStats struct {
	CPUPercentage    float64
	MemoryPercentage float64
}

// ContainerStats autogenerated at https://mholt.github.io/json-to-go/
type ContainerStats struct {
	Read      time.Time `json:"read"`
	Preread   time.Time `json:"preread"`
	PidsStats struct {
		Current int `json:"current"`
	} `json:"pids_stats"`
	BlkioStats struct {
		IoServiceBytesRecursive []struct {
			Major int    `json:"major"`
			Minor int    `json:"minor"`
			Op    string `json:"op"`
			Value int    `json:"value"`
		} `json:"io_service_bytes_recursive"`
		IoServicedRecursive []struct {
			Major int    `json:"major"`
			Minor int    `json:"minor"`
			Op    string `json:"op"`
			Value int    `json:"value"`
		} `json:"io_serviced_recursive"`
		IoQueueRecursive       []interface{} `json:"io_queue_recursive"`
		IoServiceTimeRecursive []interface{} `json:"io_service_time_recursive"`
		IoWaitTimeRecursive    []interface{} `json:"io_wait_time_recursive"`
		IoMergedRecursive      []interface{} `json:"io_merged_recursive"`
		IoTimeRecursive        []interface{} `json:"io_time_recursive"`
		SectorsRecursive       []interface{} `json:"sectors_recursive"`
	} `json:"blkio_stats"`
	NumProcs     int      `json:"num_procs"`
	StorageStats struct{} `json:"storage_stats"`
	CPUStats     struct {
		CPUUsage struct {
			TotalUsage        int64   `json:"total_usage"`
			PercpuUsage       []int64 `json:"percpu_usage"`
			UsageInKernelmode int64   `json:"usage_in_kernelmode"`
			UsageInUsermode   int64   `json:"usage_in_usermode"`
		} `json:"cpu_usage"`
		SystemCPUUsage int64 `json:"system_cpu_usage"`
		OnlineCpus     int   `json:"online_cpus"`
		ThrottlingData struct {
			Periods          int `json:"periods"`
			ThrottledPeriods int `json:"throttled_periods"`
			ThrottledTime    int `json:"throttled_time"`
		} `json:"throttling_data"`
	} `json:"cpu_stats"`
	PrecpuStats struct {
		CPUUsage struct {
			TotalUsage        int64   `json:"total_usage"`
			PercpuUsage       []int64 `json:"percpu_usage"`
			UsageInKernelmode int64   `json:"usage_in_kernelmode"`
			UsageInUsermode   int64   `json:"usage_in_usermode"`
		} `json:"cpu_usage"`
		SystemCPUUsage int64 `json:"system_cpu_usage"`
		OnlineCpus     int   `json:"online_cpus"`
		ThrottlingData struct {
			Periods          int `json:"periods"`
			ThrottledPeriods int `json:"throttled_periods"`
			ThrottledTime    int `json:"throttled_time"`
		} `json:"throttling_data"`
	} `json:"precpu_stats"`
	MemoryStats struct {
		Usage    int `json:"usage"`
		MaxUsage int `json:"max_usage"`
		Stats    struct {
			ActiveAnon              int   `json:"active_anon"`
			ActiveFile              int   `json:"active_file"`
			Cache                   int   `json:"cache"`
			Dirty                   int   `json:"dirty"`
			HierarchicalMemoryLimit int64 `json:"hierarchical_memory_limit"`
			HierarchicalMemswLimit  int64 `json:"hierarchical_memsw_limit"`
			InactiveAnon            int   `json:"inactive_anon"`
			InactiveFile            int   `json:"inactive_file"`
			MappedFile              int   `json:"mapped_file"`
			Pgfault                 int   `json:"pgfault"`
			Pgmajfault              int   `json:"pgmajfault"`
			Pgpgin                  int   `json:"pgpgin"`
			Pgpgout                 int   `json:"pgpgout"`
			Rss                     int   `json:"rss"`
			RssHuge                 int   `json:"rss_huge"`
			TotalActiveAnon         int   `json:"total_active_anon"`
			TotalActiveFile         int   `json:"total_active_file"`
			TotalCache              int   `json:"total_cache"`
			TotalDirty              int   `json:"total_dirty"`
			TotalInactiveAnon       int   `json:"total_inactive_anon"`
			TotalInactiveFile       int   `json:"total_inactive_file"`
			TotalMappedFile         int   `json:"total_mapped_file"`
			TotalPgfault            int   `json:"total_pgfault"`
			TotalPgmajfault         int   `json:"total_pgmajfault"`
			TotalPgpgin             int   `json:"total_pgpgin"`
			TotalPgpgout            int   `json:"total_pgpgout"`
			TotalRss                int   `json:"total_rss"`
			TotalRssHuge            int   `json:"total_rss_huge"`
			TotalUnevictable        int   `json:"total_unevictable"`
			TotalWriteback          int   `json:"total_writeback"`
			Unevictable             int   `json:"unevictable"`
			Writeback               int   `json:"writeback"`
		} `json:"stats"`
		Limit int64 `json:"limit"`
	} `json:"memory_stats"`
	Name     string `json:"name"`
	ID       string `json:"id"`
	Networks struct {
		Eth0 struct {
			RxBytes   int `json:"rx_bytes"`
			RxPackets int `json:"rx_packets"`
			RxErrors  int `json:"rx_errors"`
			RxDropped int `json:"rx_dropped"`
			TxBytes   int `json:"tx_bytes"`
			TxPackets int `json:"tx_packets"`
			TxErrors  int `json:"tx_errors"`
			TxDropped int `json:"tx_dropped"`
		} `json:"eth0"`
	} `json:"networks"`
}

// CalculateContainerCPUPercentage calculates the cpu usage of the container as a percent of total CPU usage
// to calculate CPU usage, we take the increase in CPU time from the container since the last poll, divide that by the total increase in CPU time since the last poll, times by the number of cores, and times by 100 to get a percentage
// I'm not entirely sure why we need to multiply by the number of cores, but the numbers work
func (s *ContainerStats) CalculateContainerCPUPercentage() float64 {
	cpuUsageDelta := s.CPUStats.CPUUsage.TotalUsage - s.PrecpuStats.CPUUsage.TotalUsage
	cpuTotalUsageDelta := s.CPUStats.SystemCPUUsage - s.PrecpuStats.SystemCPUUsage

	value := float64(cpuUsageDelta*100) / float64(cpuTotalUsageDelta)
	if math.IsNaN(value) {
		return 0
	}
	return value
}

// CalculateContainerMemoryUsage calculates the memory usage of the container as a percent of total available memory
func (s *ContainerStats) CalculateContainerMemoryUsage() float64 {
	value := float64(s.MemoryStats.Usage*100) / float64(s.MemoryStats.Limit)
	if math.IsNaN(value) {
		return 0
	}
	return value
}

func (c *Container) appendStats(stats *RecordedStats, maxDuration time.Duration) {
	c.StatsMutex.Lock()
	defer c.StatsMutex.Unlock()

	c.StatHistory = append(c.StatHistory, stats)
	c.eraseOldHistory(maxDuration)
}

// eraseOldHistory removes any history before the user-specified max duration
func (c *Container) eraseOldHistory(maxDuration time.Duration) {
	if maxDuration == 0 {
		return
	}

	for i, stat := range c.StatHistory {
		if time.Since(stat.RecordedAt) < maxDuration {
			c.StatHistory = c.StatHistory[i:]
			return
		}
	}
}

func (c *Container) GetLastStats() (*RecordedStats, bool) {
	c.StatsMutex.Lock()
	defer c.StatsMutex.Unlock()
	history := c.StatHistory
	if len(history) == 0 {
		return nil, false
	}
	return history[len(history)-1], true
}
